### PR TITLE
Add author field subsitution

### PR DESCRIPTION
**Pull request by sdavids**

### CODE REVIEW

**Comment by adoble** [comment]
Running the JUnit tests on this PR with Windows10 and none of the author environment variables set I get test failures with testRecordConstructionWithDefaultAuthor and testRecordConstructionWithGivenAuthor. Reason is:

```
org.doble.adr.ADRException: Cannot get the template containing {{{link.id}}}
	at org.doble.adr.Record.getFragment(Record.java:303)
             … 
```

**Comment by sdavids** [comment]
I guess it is related to  0c6d761 ... in order to run it on Mac I had to introduce that fix.

**Comment by sdavids** [comment]
I also noticed that you do not run the tests during a gradle build ...

I had to add the following to _build.gradle_:

``` groovy
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
```

**Comment by sdavids** [comment]
Currently you have a dependency on `org.reflections:reflections` (even though you do not use it) which has a transitive dependency on `com.google.guava:guava`.

You might want to refactor the template loading to use:

https://guava.dev/releases/20.0/api/docs/com/google/common/io/Resources.html

**Comment by sdavids** [comment]
I ran this PR with the fix in PR #29 i.e. I ran tests on both Linux and Windows VMs and they were both green:

https://travis-ci.org/adoble/adr-j/builds/609926927

The problem you mention in https://github.com/adoble/adr-j/pull/24#issuecomment-552124370 seems to be an issue with your local setup then ... which is still not good 😉

**Comment by sdavids** [comment]
Please merge #29  first .. I will rebase this PR afterwards ...

**Pull request merged**
